const urlPath = {
    login: `/auth/login`,
    varifyEmail: `/user/isVarifyEmail`,
    setPassword: `/user/setPassword`,
    home: '/user/getEmployee',
    profile: `/user`,
    getUserById: `/user/getUser`,
    update: `/user`,
    register: `/auth/register`,
    createLeaveRecord: `/leaveRecord/createRecord`,
    getLeaveTypeById: `/leaveType`,
    getLeaveRecord: `/leaveRecord/getAllRecord`,
    particularLeaveRecord: `/leaveRecord/getParticularRecord`,
    updateLeaveRecord: `/leaveRecord`,
    applyLeaveRequest: `/leaveRequest`,
    getRequestByManagerId: '/leaveRequest',
    getRequestByRequestId: '/leaveRequest/getRequest',
    changeRequestStatus: '/leaveRequest/changeStatus',
    getRequestByUserId: '/leaveRequest/userRequest',
    addCommentInRequest: `/leaveRequest`,
    getRequestByStatus: '/leaveRequest/getByStatus',
    changePassword: '/user/changePassword',
    getCompensantoryRequest: '/leaveRequest/getCompensantoryRequest',
    getRequestByManagerIdAndStatus: `/leaveRequest/getByManagerIdAndStatus`,
    getByRole: `/user/getByRole`,
    getNotification: `/notification`,
    createNotification: `/notification`,
    updateNotification: `/notification`,
    updateAllNotification: `/notification/updateAll`,
}

export default urlPath;